/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard.settings'
import { Route as AuthenticatedDashboardOrganizationRouteImport } from './routes/_authenticated/dashboard.organization'
import { Route as AuthenticatedDashboardLibraryRouteImport } from './routes/_authenticated/dashboard.library'
import { Route as AuthenticatedDashboardBillingRouteImport } from './routes/_authenticated/dashboard.billing'
import { Route as AuthenticatedDashboardAnalyticsRouteImport } from './routes/_authenticated/dashboard.analytics'
import { Route as AuthenticatedAdminPostsRouteImport } from './routes/_authenticated/admin.posts'
import { Route as AuthenticatedAdminAccountsRouteImport } from './routes/_authenticated/admin.accounts'
import { Route as AuthenticatedDashboardOrdersIndexRouteImport } from './routes/_authenticated/dashboard.orders.index'
import { Route as AuthenticatedDashboardAccountsIndexRouteImport } from './routes/_authenticated/dashboard.accounts.index'
import { Route as ApiPublicWebhooksWhopRouteImport } from './routes/api/public/webhooks/whop'
import { Route as ApiPublicAdminBunnyDownloadRouteImport } from './routes/api/public/admin/bunny-download'
import { Route as AuthenticatedDashboardOrdersNewRouteImport } from './routes/_authenticated/dashboard.orders.new'
import { Route as AuthenticatedDashboardAccountsIdRouteImport } from './routes/_authenticated/dashboard.accounts.$id'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOrganizationRoute =
  AuthenticatedDashboardOrganizationRouteImport.update({
    id: '/dashboard/organization',
    path: '/dashboard/organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardLibraryRoute =
  AuthenticatedDashboardLibraryRouteImport.update({
    id: '/dashboard/library',
    path: '/dashboard/library',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardBillingRoute =
  AuthenticatedDashboardBillingRouteImport.update({
    id: '/dashboard/billing',
    path: '/dashboard/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAnalyticsRoute =
  AuthenticatedDashboardAnalyticsRouteImport.update({
    id: '/dashboard/analytics',
    path: '/dashboard/analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPostsRoute = AuthenticatedAdminPostsRouteImport.update({
  id: '/admin/posts',
  path: '/admin/posts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAccountsRoute =
  AuthenticatedAdminAccountsRouteImport.update({
    id: '/admin/accounts',
    path: '/admin/accounts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardOrdersIndexRoute =
  AuthenticatedDashboardOrdersIndexRouteImport.update({
    id: '/dashboard/orders/',
    path: '/dashboard/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAccountsIndexRoute =
  AuthenticatedDashboardAccountsIndexRouteImport.update({
    id: '/dashboard/accounts/',
    path: '/dashboard/accounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicWebhooksWhopRoute = ApiPublicWebhooksWhopRouteImport.update({
  id: '/api/public/webhooks/whop',
  path: '/api/public/webhooks/whop',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminBunnyDownloadRoute =
  ApiPublicAdminBunnyDownloadRouteImport.update({
    id: '/api/public/admin/bunny-download',
    path: '/api/public/admin/bunny-download',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedDashboardOrdersNewRoute =
  AuthenticatedDashboardOrdersNewRouteImport.update({
    id: '/dashboard/orders/new',
    path: '/dashboard/orders/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardAccountsIdRoute =
  AuthenticatedDashboardAccountsIdRouteImport.update({
    id: '/dashboard/accounts/$id',
    path: '/dashboard/accounts/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/dashboard/organization': typeof AuthenticatedDashboardOrganizationRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/accounts/$id': typeof AuthenticatedDashboardAccountsIdRoute
  '/dashboard/orders/new': typeof AuthenticatedDashboardOrdersNewRoute
  '/api/public/admin/bunny-download': typeof ApiPublicAdminBunnyDownloadRoute
  '/api/public/webhooks/whop': typeof ApiPublicWebhooksWhopRoute
  '/dashboard/accounts/': typeof AuthenticatedDashboardAccountsIndexRoute
  '/dashboard/orders/': typeof AuthenticatedDashboardOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/dashboard/organization': typeof AuthenticatedDashboardOrganizationRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/accounts/$id': typeof AuthenticatedDashboardAccountsIdRoute
  '/dashboard/orders/new': typeof AuthenticatedDashboardOrdersNewRoute
  '/api/public/admin/bunny-download': typeof ApiPublicAdminBunnyDownloadRoute
  '/api/public/webhooks/whop': typeof ApiPublicWebhooksWhopRoute
  '/dashboard/accounts': typeof AuthenticatedDashboardAccountsIndexRoute
  '/dashboard/orders': typeof AuthenticatedDashboardOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invitation': typeof AcceptInvitationRoute
  '/auth': typeof AuthRoute
  '/pricing': typeof PricingRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/admin/accounts': typeof AuthenticatedAdminAccountsRoute
  '/_authenticated/admin/posts': typeof AuthenticatedAdminPostsRoute
  '/_authenticated/dashboard/analytics': typeof AuthenticatedDashboardAnalyticsRoute
  '/_authenticated/dashboard/billing': typeof AuthenticatedDashboardBillingRoute
  '/_authenticated/dashboard/library': typeof AuthenticatedDashboardLibraryRoute
  '/_authenticated/dashboard/organization': typeof AuthenticatedDashboardOrganizationRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/accounts/$id': typeof AuthenticatedDashboardAccountsIdRoute
  '/_authenticated/dashboard/orders/new': typeof AuthenticatedDashboardOrdersNewRoute
  '/api/public/admin/bunny-download': typeof ApiPublicAdminBunnyDownloadRoute
  '/api/public/webhooks/whop': typeof ApiPublicWebhooksWhopRoute
  '/_authenticated/dashboard/accounts/': typeof AuthenticatedDashboardAccountsIndexRoute
  '/_authenticated/dashboard/orders/': typeof AuthenticatedDashboardOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/pricing'
    | '/sign-up'
    | '/onboarding'
    | '/admin/accounts'
    | '/admin/posts'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/library'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/accounts/$id'
    | '/dashboard/orders/new'
    | '/api/public/admin/bunny-download'
    | '/api/public/webhooks/whop'
    | '/dashboard/accounts/'
    | '/dashboard/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/auth'
    | '/pricing'
    | '/sign-up'
    | '/onboarding'
    | '/admin/accounts'
    | '/admin/posts'
    | '/dashboard/analytics'
    | '/dashboard/billing'
    | '/dashboard/library'
    | '/dashboard/organization'
    | '/dashboard/settings'
    | '/admin'
    | '/dashboard'
    | '/dashboard/accounts/$id'
    | '/dashboard/orders/new'
    | '/api/public/admin/bunny-download'
    | '/api/public/webhooks/whop'
    | '/dashboard/accounts'
    | '/dashboard/orders'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/accept-invitation'
    | '/auth'
    | '/pricing'
    | '/sign-up'
    | '/_authenticated/onboarding'
    | '/_authenticated/admin/accounts'
    | '/_authenticated/admin/posts'
    | '/_authenticated/dashboard/analytics'
    | '/_authenticated/dashboard/billing'
    | '/_authenticated/dashboard/library'
    | '/_authenticated/dashboard/organization'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/accounts/$id'
    | '/_authenticated/dashboard/orders/new'
    | '/api/public/admin/bunny-download'
    | '/api/public/webhooks/whop'
    | '/_authenticated/dashboard/accounts/'
    | '/_authenticated/dashboard/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  AuthRoute: typeof AuthRoute
  PricingRoute: typeof PricingRoute
  SignUpRoute: typeof SignUpRoute
  ApiPublicAdminBunnyDownloadRoute: typeof ApiPublicAdminBunnyDownloadRoute
  ApiPublicWebhooksWhopRoute: typeof ApiPublicWebhooksWhopRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/organization': {
      id: '/_authenticated/dashboard/organization'
      path: '/dashboard/organization'
      fullPath: '/dashboard/organization'
      preLoaderRoute: typeof AuthenticatedDashboardOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/library': {
      id: '/_authenticated/dashboard/library'
      path: '/dashboard/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof AuthenticatedDashboardLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/billing': {
      id: '/_authenticated/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof AuthenticatedDashboardBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/analytics': {
      id: '/_authenticated/dashboard/analytics'
      path: '/dashboard/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof AuthenticatedDashboardAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/posts': {
      id: '/_authenticated/admin/posts'
      path: '/admin/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AuthenticatedAdminPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/accounts': {
      id: '/_authenticated/admin/accounts'
      path: '/admin/accounts'
      fullPath: '/admin/accounts'
      preLoaderRoute: typeof AuthenticatedAdminAccountsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/orders/': {
      id: '/_authenticated/dashboard/orders/'
      path: '/dashboard/orders'
      fullPath: '/dashboard/orders/'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/accounts/': {
      id: '/_authenticated/dashboard/accounts/'
      path: '/dashboard/accounts'
      fullPath: '/dashboard/accounts/'
      preLoaderRoute: typeof AuthenticatedDashboardAccountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/whop': {
      id: '/api/public/webhooks/whop'
      path: '/api/public/webhooks/whop'
      fullPath: '/api/public/webhooks/whop'
      preLoaderRoute: typeof ApiPublicWebhooksWhopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/bunny-download': {
      id: '/api/public/admin/bunny-download'
      path: '/api/public/admin/bunny-download'
      fullPath: '/api/public/admin/bunny-download'
      preLoaderRoute: typeof ApiPublicAdminBunnyDownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/orders/new': {
      id: '/_authenticated/dashboard/orders/new'
      path: '/dashboard/orders/new'
      fullPath: '/dashboard/orders/new'
      preLoaderRoute: typeof AuthenticatedDashboardOrdersNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/accounts/$id': {
      id: '/_authenticated/dashboard/accounts/$id'
      path: '/dashboard/accounts/$id'
      fullPath: '/dashboard/accounts/$id'
      preLoaderRoute: typeof AuthenticatedDashboardAccountsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminAccountsRoute: typeof AuthenticatedAdminAccountsRoute
  AuthenticatedAdminPostsRoute: typeof AuthenticatedAdminPostsRoute
  AuthenticatedDashboardAnalyticsRoute: typeof AuthenticatedDashboardAnalyticsRoute
  AuthenticatedDashboardBillingRoute: typeof AuthenticatedDashboardBillingRoute
  AuthenticatedDashboardLibraryRoute: typeof AuthenticatedDashboardLibraryRoute
  AuthenticatedDashboardOrganizationRoute: typeof AuthenticatedDashboardOrganizationRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDashboardAccountsIdRoute: typeof AuthenticatedDashboardAccountsIdRoute
  AuthenticatedDashboardOrdersNewRoute: typeof AuthenticatedDashboardOrdersNewRoute
  AuthenticatedDashboardAccountsIndexRoute: typeof AuthenticatedDashboardAccountsIndexRoute
  AuthenticatedDashboardOrdersIndexRoute: typeof AuthenticatedDashboardOrdersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminAccountsRoute: AuthenticatedAdminAccountsRoute,
  AuthenticatedAdminPostsRoute: AuthenticatedAdminPostsRoute,
  AuthenticatedDashboardAnalyticsRoute: AuthenticatedDashboardAnalyticsRoute,
  AuthenticatedDashboardBillingRoute: AuthenticatedDashboardBillingRoute,
  AuthenticatedDashboardLibraryRoute: AuthenticatedDashboardLibraryRoute,
  AuthenticatedDashboardOrganizationRoute:
    AuthenticatedDashboardOrganizationRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDashboardAccountsIdRoute: AuthenticatedDashboardAccountsIdRoute,
  AuthenticatedDashboardOrdersNewRoute: AuthenticatedDashboardOrdersNewRoute,
  AuthenticatedDashboardAccountsIndexRoute:
    AuthenticatedDashboardAccountsIndexRoute,
  AuthenticatedDashboardOrdersIndexRoute:
    AuthenticatedDashboardOrdersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInvitationRoute: AcceptInvitationRoute,
  AuthRoute: AuthRoute,
  PricingRoute: PricingRoute,
  SignUpRoute: SignUpRoute,
  ApiPublicAdminBunnyDownloadRoute: ApiPublicAdminBunnyDownloadRoute,
  ApiPublicWebhooksWhopRoute: ApiPublicWebhooksWhopRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
